version: '3.8'
services:
  app:
    build:
      dockerfile: build/Dockerfile
      context: .
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ../../postgresql:/var/lib/postgresql/data
