// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bojik/sqlmigrator/pkg/db (interfaces: DataKeeper)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	db "github.com/bojik/sqlmigrator/pkg/db"
	gomock "github.com/golang/mock/gomock"
)

// MockDataKeeper is a mock of DataKeeper interface.
type MockDataKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockDataKeeperMockRecorder
}

// MockDataKeeperMockRecorder is the mock recorder for MockDataKeeper.
type MockDataKeeperMockRecorder struct {
	mock *MockDataKeeper
}

// NewMockDataKeeper creates a new mock instance.
func NewMockDataKeeper(ctrl *gomock.Controller) *MockDataKeeper {
	mock := &MockDataKeeper{ctrl: ctrl}
	mock.recorder = &MockDataKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataKeeper) EXPECT() *MockDataKeeperMockRecorder {
	return m.recorder
}

// CreateMigratorTable mocks base method.
func (m *MockDataKeeper) CreateMigratorTable() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMigratorTable")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMigratorTable indicates an expected call of CreateMigratorTable.
func (mr *MockDataKeeperMockRecorder) CreateMigratorTable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMigratorTable", reflect.TypeOf((*MockDataKeeper)(nil).CreateMigratorTable))
}

// DeleteByVersion mocks base method.
func (m *MockDataKeeper) DeleteByVersion(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByVersion", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByVersion indicates an expected call of DeleteByVersion.
func (mr *MockDataKeeperMockRecorder) DeleteByVersion(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByVersion", reflect.TypeOf((*MockDataKeeper)(nil).DeleteByVersion), arg0)
}

// ExecSQL mocks base method.
func (m *MockDataKeeper) ExecSQL(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecSQL", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecSQL indicates an expected call of ExecSQL.
func (mr *MockDataKeeperMockRecorder) ExecSQL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecSQL", reflect.TypeOf((*MockDataKeeper)(nil).ExecSQL), arg0)
}

// FindLastVersion mocks base method.
func (m *MockDataKeeper) FindLastVersion() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLastVersion")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLastVersion indicates an expected call of FindLastVersion.
func (mr *MockDataKeeperMockRecorder) FindLastVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLastVersion", reflect.TypeOf((*MockDataKeeper)(nil).FindLastVersion))
}

// FindNewMigrations mocks base method.
func (m *MockDataKeeper) FindNewMigrations(arg0 []int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNewMigrations", arg0)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNewMigrations indicates an expected call of FindNewMigrations.
func (mr *MockDataKeeperMockRecorder) FindNewMigrations(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNewMigrations", reflect.TypeOf((*MockDataKeeper)(nil).FindNewMigrations), arg0)
}

// FindVersionStatusByVersion mocks base method.
func (m *MockDataKeeper) FindVersionStatusByVersion(arg0 int) (db.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindVersionStatusByVersion", arg0)
	ret0, _ := ret[0].(db.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindVersionStatusByVersion indicates an expected call of FindVersionStatusByVersion.
func (mr *MockDataKeeperMockRecorder) FindVersionStatusByVersion(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindVersionStatusByVersion", reflect.TypeOf((*MockDataKeeper)(nil).FindVersionStatusByVersion), arg0)
}

// GetVersionsByStatus mocks base method.
func (m *MockDataKeeper) GetVersionsByStatus(arg0 db.Status) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersionsByStatus", arg0)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersionsByStatus indicates an expected call of GetVersionsByStatus.
func (mr *MockDataKeeperMockRecorder) GetVersionsByStatus(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersionsByStatus", reflect.TypeOf((*MockDataKeeper)(nil).GetVersionsByStatus), arg0)
}

// SelectRows mocks base method.
func (m *MockDataKeeper) SelectRows() ([]db.Row, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectRows")
	ret0, _ := ret[0].([]db.Row)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectRows indicates an expected call of SelectRows.
func (mr *MockDataKeeperMockRecorder) SelectRows() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectRows", reflect.TypeOf((*MockDataKeeper)(nil).SelectRows))
}

// SelectVersionRow mocks base method.
func (m *MockDataKeeper) SelectVersionRow(arg0 int) (db.VersionRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectVersionRow", arg0)
	ret0, _ := ret[0].(db.VersionRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectVersionRow indicates an expected call of SelectVersionRow.
func (mr *MockDataKeeperMockRecorder) SelectVersionRow(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectVersionRow", reflect.TypeOf((*MockDataKeeper)(nil).SelectVersionRow), arg0)
}
