name: SQL Migrator tests

on:
  push:
    branches:
      - develop

env:
  GO111MODULE: "on"

jobs:
  go_get:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

  tests_by_makefile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Check out code
        uses: actions/checkout@v2

      - name: make lint
        run: make lint

      - name: make build
        run: make build

      - name: make test
        run: make test

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: make test-integration
        run: make test-integration
